{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .appName }}
  ports:
  - protocol: TCP
    port: {{ .servicePort }}
    targetPort: {{ .port }}
---
{{- end }}